repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: "__snapshots__/"
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: "__snapshots__/"
      - id: pretty-format-json
        args: [--autofix]
        exclude: "__snapshots__/"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.5  # 請根據需求調整到你希望使用的版本
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=120
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        types: [python]
        exclude: migrations/|commands/|sandbox/|samples|sdk
        additional_dependencies: [pytest, syrupy, types-Pillow, typer, jinja2, types-beautifulsoup4, devtools, html2text]
        args: [
          "--config-file=pyproject.toml"
        ]
