exclude = [
    # ipynb
    "*.ipynb",
    # directories
    "**/__snapshots__/",
    ".github/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".venv/",
    "venv/",
    # Submodules.
    "ffmpeg/",
]

[lint]
preview = true
select = [
    "E",       # pycodestyle errors
    "W",       # pycodestyle warnings
    "F",       # pyflakes
    "I",       # isort
    "B",       # flake8-bugbear
    "B006",    # flake8-bugbear: Do not use mutable data structures for argument defaults
    "C4",      # flake8-comprehensions
    "UP",      # pyupgrade
    # "TID252",  # Ban Relative Import https://docs.astral.sh/ruff/rules/relative-imports/#relative-imports-tid252
]
ignore = ["B008", "E501"]
